services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app
    ports:
      - "3254:3254"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql